04-07 10:16:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "PIECE" not found; SQL statement:
select idpiece, nomserveur, positionX, positionY from PIECE [42102-147]
04-24 14:53:05 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "YouYou" not found; SQL statement:
insert into UTILISATEUR values (1, "YouYou", "1234") [42122-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:126)
	at org.h2.command.dml.Insert.prepare(Insert.java:224)
	at org.h2.command.Parser.prepare(Parser.java:202)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1056)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:165)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1004)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:970)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
04-24 14:54:11 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "YouYou" not found; SQL statement:
insert into UTILISATEUR (IDUTILISATEUR, NOMUTILISATEUR, MDPUTILISATEUR) values (1, "YouYou", "1234") [42122-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:126)
	at org.h2.command.dml.Insert.prepare(Insert.java:224)
	at org.h2.command.Parser.prepare(Parser.java:202)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1056)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:165)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1004)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:970)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
04-24 14:58:22 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:213)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1259)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:323)
	at persistence.LabyrintheJDBC.selectUtilisateurByNom(LabyrintheJDBC.java:137)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:245)
04-24 14:58:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:213)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1259)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:323)
	at persistence.LabyrintheJDBC.selectUtilisateurByNom(LabyrintheJDBC.java:137)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:245)
04-24 15:04:38 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:213)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1259)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:323)
	at persistence.LabyrintheJDBC.selectUtilisateurByNom(LabyrintheJDBC.java:137)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:245)
04-26 21:48:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "PersoDeYouYou" not found; SQL statement:
insert into PERSONNAGE (NOMPERSONNAGE , IDUTILISATEUR , POINTVIE , IDPIECE ) values ("PersoDeYouYou", 1, 10, 1) [42122-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:126)
	at org.h2.command.dml.Insert.prepare(Insert.java:224)
	at org.h2.command.Parser.prepare(Parser.java:202)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1056)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:165)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1004)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:970)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
04-26 21:49:38 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "IDPIECE" not found; SQL statement:
select * from IDPIECE [42102-147]
