04-07 10:16:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "PIECE" not found; SQL statement:
select idpiece, nomserveur, positionX, positionY from PIECE [42102-147]
04-24 14:53:05 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "YouYou" not found; SQL statement:
insert into UTILISATEUR values (1, "YouYou", "1234") [42122-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:126)
	at org.h2.command.dml.Insert.prepare(Insert.java:224)
	at org.h2.command.Parser.prepare(Parser.java:202)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1056)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:165)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1004)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:970)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
04-24 14:54:11 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "YouYou" not found; SQL statement:
insert into UTILISATEUR (IDUTILISATEUR, NOMUTILISATEUR, MDPUTILISATEUR) values (1, "YouYou", "1234") [42122-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:126)
	at org.h2.command.dml.Insert.prepare(Insert.java:224)
	at org.h2.command.Parser.prepare(Parser.java:202)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1056)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:165)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1004)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:970)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
04-24 14:58:22 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:213)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1259)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:323)
	at persistence.LabyrintheJDBC.selectUtilisateurByNom(LabyrintheJDBC.java:137)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:245)
04-24 14:58:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:213)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1259)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:323)
	at persistence.LabyrintheJDBC.selectUtilisateurByNom(LabyrintheJDBC.java:137)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:245)
04-24 15:04:38 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:213)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1259)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:323)
	at persistence.LabyrintheJDBC.selectUtilisateurByNom(LabyrintheJDBC.java:137)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:245)
04-26 21:48:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "PersoDeYouYou" not found; SQL statement:
insert into PERSONNAGE (NOMPERSONNAGE , IDUTILISATEUR , POINTVIE , IDPIECE ) values ("PersoDeYouYou", 1, 10, 1) [42122-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:126)
	at org.h2.command.dml.Insert.prepare(Insert.java:224)
	at org.h2.command.Parser.prepare(Parser.java:202)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1056)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:165)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1004)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:970)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
04-26 21:49:38 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "IDPIECE" not found; SQL statement:
select * from IDPIECE [42102-147]
04-30 21:12:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM PIECE 
DELETE FROM[*] PIECE "; SQL statement:
select * from PIECE 
delete from PIECE [42000-147]
04-30 21:18:11 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "              
INSERT INTO PIECE (IDPIECE, NOMSERVEUR , POSITIONX , POSITIONY ) VALUES (14, 'beta', 2, 6)
INSERT[*] INTO PORTE (SITUATIONPORTE , IDPIECE ) VALUES ('NORD', 14) "; SQL statement:
-- Salle 14 --
insert into PIECE (IDPIECE, NOMSERVEUR , POSITIONX , POSITIONY ) values (14, 'beta', 2, 6)
insert into PORTE (SITUATIONPORTE , IDPIECE ) values ('NORD', 14) [42000-147]
05-07 12:43:52 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-07 12:49:11 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-07 12:51:04 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-07 12:57:28 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-07 12:59:19 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-07 13:15:33 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-07 13:16:27 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-07 13:17:19 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-07 13:23:19 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-07 13:29:44 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-07 13:32:02 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:61)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:222)
	at Game.main(Game.java:8)
05-18 19:01:14 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:63)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:245)
	at Game.main(Game.java:8)
05-18 19:02:57 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:63)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:245)
	at Game.main(Game.java:8)
05-25 19:12:51 jdbc[2]: connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at persistence.LabyrintheJDBC.<init>(LabyrintheJDBC.java:70)
	at persistence.LabyrintheJDBC.main(LabyrintheJDBC.java:313)
	at Partie.main(Partie.java:8)
05-25 23:11:40 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM MONSTRE SORT BY[*] IDPIECE "; SQL statement:
select * from monstre sort by idPiece [42000-147]
05-25 23:13:17 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE MONSTRE WHERE[*] IDMONSTRE = 1
SET POINTVIE = 5 AND IDPIECE = 1 AND NOMMONSTRE = 'Slimaze' "; expected "SET"; SQL statement:
update monstre where idmonstre = 1
set pointvie = 5 and idpiece = 1 and nommonstre = 'Slimaze' [42001-147]
05-25 23:14:57 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "Slimaze" not found; SQL statement:
update monstre
set nommonstre = "Slimaze"
where idMonstre = 1 [42122-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:126)
	at org.h2.command.dml.Update.prepare(Update.java:170)
	at org.h2.command.Parser.prepare(Parser.java:202)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1056)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:165)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1004)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:970)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
